# Generated by Django 2.0.5 on 2018-10-11 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_airline', models.CharField(max_length=100)),
                ('flight_dept_code', models.CharField(max_length=10)),
                ('flight_dept_city', models.CharField(max_length=100)),
                ('flight_arrival_code', models.CharField(max_length=10)),
                ('flight_arrival_city', models.CharField(max_length=100)),
                ('flight_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Flight')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Hotel')),
            ],
        ),
    ]
