# Generated by Django 2.0.5 on 2018-10-11 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20181010_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_dept_date', models.DateField(default=django.utils.timezone.now)),
                ('trip_dept_city', models.CharField(max_length=100)),
                ('trip_dest_city', models.CharField(max_length=100)),
                ('trip_ret_date', models.DateField(default=django.utils.timezone.now)),
                ('trip_dept_iata', models.CharField(max_length=5)),
                ('trip_dest_iata', models.CharField(max_length=5)),
            ],
        ),
    ]
